ARG CUDA_VER='11.2.1'
FROM nvidia/cuda:${CUDA_VER}-devel-ubuntu20.04
#==============================================================================
ARG TORCH_UCC_ROOT_DIR=/opt/nvidia/torch-ucc
ENV TORCH_UCC_SRC_DIR=${TORCH_UCC_ROOT_DIR}/src
ENV TORCH_UCC_PKG_DIR=${TORCH_UCC_ROOT_DIR}/pkg
ENV TORCH_UCC_BIN_DIR=${TORCH_UCC_ROOT_DIR}/bin
ENV CUDA_HOME=/usr/local/cuda
ENV UCX_BRANCH=v1.10.x
ENV UCX_BUILD_TYPE=release-mt
ENV UCX_INSTALL_DIR=${TORCH_UCC_BIN_DIR}/ucx/build-${UCX_BUILD_TYPE}
ENV XCCL_BUILD_TYPE=debug
ENV XCCL_INSTALL_DIR=${TORCH_UCC_BIN_DIR}/xccl/build-${XCCL_BUILD_TYPE}
#==============================================================================
RUN mkdir -p ${TORCH_UCC_SRC_DIR} && \
    mkdir -p ${TORCH_UCC_PKG_DIR} && \
    mkdir -p ${TORCH_UCC_BIN_DIR}

#COPY . ${TORCH_UCC_SRC_DIR}
##==============================================================================
#ARG DEBIAN_FRONTEND=noninteractive
#RUN apt update && \
#    apt install -y \
#        apt-utils \
#        autoconf \
#        build-essential \
#        cmake \
#        curl \
#        git \
#        ibverbs-providers \
#        ibverbs-utils \
#        libnuma-dev \
#        libtool-bin \
#        ninja-build \
#        openmpi-bin \
#        vim \
#    && \
#    rm -rf /var/lib/apt/lists/*
##==============================================================================
## Build UCX
#RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/build_ucx.sh
#ENV PATH=${UCX_INSTALL_DIR}/bin:${PATH}
##==============================================================================
## Configure Python
#RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/configure_python.sh
#ENV PATH /opt/conda/bin:${PATH}
##==============================================================================
## Build XCCL
#RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/build_xccl.sh
##==============================================================================
## Install PyTorch
#RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/install_torch.sh
##==============================================================================
## Install torch_ucc python module and build a wheel package
#RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/install_torch_ucc.sh
##==============================================================================
