FROM nvidia/cuda:11.2.1-devel-ubuntu20.04

ARG TORCH_UCC_SRC_DIR='/opt/nvidia/torch-ucc/src'
ARG TORCH_UCC_PKG_DIR='/opt/nvidia/torch-ucc/pkg'
ARG TORCH_UCC_BIN_DIR='/opt/nvidia/torch-ucc/bin'
ARG CUDA_HOME='/usr/local/cuda'
ARG UCX_BRANCH='v1.10.x'
ARG UCX_INSTALL_DIR='/opt/nvidia/torch-ucc/bin/ucx'
#ARG UCX_BUILD_TYPE='debug'
ARG UCX_BUILD_TYPE='release-mt'

RUN mkdir -p ${TORCH_UCC_SRC_DIR} && \
    mkdir -p ${TORCH_UCC_PKG_DIR} && \
    mkdir -p ${TORCH_UCC_BIN_DIR}

COPY . ${TORCH_UCC_SRC_DIR}
RUN find ${TORCH_UCC_SRC_DIR}

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y \
        apt-utils \
        autoconf \
        build-essential \
        cmake \
        curl \
        git \
        ibverbs-providers \
        ibverbs-utils \
        libnuma-dev \
        libtool-bin \
        openmpi-bin \
        vim \
    && \
    rm -rf /var/lib/apt/lists/*

# Build UCX
RUN echo "INFO: Build UCX" && \
    cd ${TORCH_UCC_SRC_DIR}/ucx && \
    git checkout ${UCX_BRANCH} && \
    ${TORCH_UCC_SRC_DIR}/ucx/autogen.sh && \
    mkdir -p ${TORCH_UCC_SRC_DIR}/ucx/build && \
    cd ${TORCH_UCC_SRC_DIR}/ucx/build && \
    #${TORCH_UCC_SRC_DIR}/ucx/configure --enable-mt --with-cuda=${CUDA_HOME} --prefix=${UCX_INSTALL_DIR}/build-${UCX_BUILD_TYPE} && \
    #${TORCH_UCC_SRC_DIR}/ucx/contrib/configure-devel --enable-mt --with-cuda=${CUDA_HOME} --prefix=${UCX_INSTALL_DIR}/build-${UCX_BUILD_TYPE} && \
    ${UCX_SRC_DIR}/contrib/configure-release-mt --with-cuda=${CUDA_HOME} --prefix=${UCX_INSTALL_DIR}/build-${UCX_BUILD_TYPE} && \
    make -j install && \
    echo "${UCX_INSTALL_DIR}/build-${UCX_BUILD_TYPE}/lib" > /etc/ld.so.conf.d/ucx.conf && \
    ldconfig && \
    ldconfig -p | grep -i ucx && \
    cd ${UCX_INSTALL_DIR} && tar cfz ${TORCH_UCC_PKG_DIR}/ucx.tgz --owner=0 --group=0 .

# Install conda
#RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
#    bash Miniconda3-latest-Linux-x86_64.sh -p /opt/conda -b && \
#    rm -f Miniconda3-latest-Linux-x86_64.sh
#ENV PATH /opt/conda/bin:${PATH}

# Install conda python
#RUN conda update -y conda && \
#    conda install -c anaconda -y \
#        python \
#        pip && \
#    pip install --no-cache-dir python-hostlist
#
#RUN ln -s /opt/conda/bin/python /usr/bin/python
#RUN python3 -m pip install --user --upgrade setuptools wheel auditwheel check-wheel-contents

# Install PyTorch
#RUN git clone https://github.com/pytorch/pytorch.git && \
#    cd pytorch && \
#    git submodule sync --recursive && \
#    git submodule update --init --recursive && \
#    pip install -r requirements.txt && \
#    TORCH_CUDA_ARCH_LIST="7.0 8.0+PTX" \
#    USE_GLOO=1 \
#    USE_DISTRIBUTED=1 \
#    USE_OPENCV=0 \
#    USE_CUDA=1 \
#    USE_NCCL=0 \
#    USE_MKLDNN=0 \
#    BUILD_TEST=0 \
#    USE_FBGEMM=0 \
#    USE_NNPACK=0 \
#    USE_QNNPACK=0 \
#    USE_XNNPACK=0 \
#    USE_KINETO=1 \
#    python setup.py install && \
#    rm -rf /workspace/pytorch
